name: pre-merge-checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1

  
  code_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "~= 22.6"

